bind:
  image: joebiellik/bind

  volumes:
    # You must provide a config file
    - ./named.conf:/etc/bind/named.conf

    # Zone files
    - ./zones:/var/lib/bind

  ports:
    - "53:53/tcp"
    - "53:53/udp"
